---
title: "Learn Coding"
author: "ale66"
format: 
  revealjs:
    footer: "[github.com/ale66/learn-coding](https://github.com/ale66/learn-coding)&nbsp;&nbsp;&nbsp;"
    theme: [moon]
    preview-links: auto
    chalkboard: 
      boardmarker-width: 2
    progress: true
from: markdown+emoji
execute:
  echo: true
---

# Auxiliary variables

---

## Topics

- counters 
  
- accumulators

- trailers


# Counters

---

A variable, normally of type integer, that is incremented as we *parse* an iterable

Example: compute list size/length

```python
l = 0

for f in fruits:

  l = l +1

print(f'The length of list {fruits} is {l}')
```

. . . 

Syntax: `l += 1` is shorthand for `l = l + 1`


--- 

## Anonymous variables

In fact, we are not operating on `f`

it can be omitted in favour of an *anonymous variable* `_`

```python
l = 0

for _ in fruits:

  l += 1

print(f'The lenght of list {fruits} is {l}')
```


# Accumulators


---

A variable to record quantities seen during the iteration

Example: the average of an arbitrary list of positive numbers


```python
l = 0
accumulator = 0

for val in mylist:
  l += 1
  accumulator += val

if l > 0:
  average =  accumulator / l # this will be a float

print(f'There are {l} values and their average is {average}')
```


# Trailing variables

---

A variable that *remembers* past values during an iteration

Example: find the biggest *temperature increase* in a list 

```python
# start with the minimum possible value
max_day_on_day_change = 0

# initialise the trailer variable
trailer = temperatures_this_month[0]

for temp in temperatures_this_month:

  # do your thing here...

  # we are finished with this value, assign it to the trailer
  trailer = temp

print(f'The maximum day-on-day increase has been {maxincrease} degrees')
```


---

## Programme comprehension

To grasp how trailers work, put extra `print()` commands to see what the variables contain

Rename variables:


```python
yesterday = temperaturelist[0]

for today in temperaturelist:

  current_increase = today - yesterday

  ...

  yesterday =  today
```

---

## A more complete encoding

```python
temperatures_this_month = [27, 21, 16, 21, 19, 18, 19, 12, 15, 12]

'''
Question: 
which day of the month has seen 
the steepest temperature change (either increasing or decreasing)?
'''
```

---


```python
# start with the minimum possible value
max_day_on_day_change = 0

# initialise the trailer variable
trailer = temperatures_this_month[0]

for temp in temperatures_this_month:

  current_change = temp - trailer
  
  if abs(current_change) > max_day_on_day_change:
  
    max_day_on_day_change = abs(current_change) # a new max is found

  # we are finished with this value, assign it to the trailer
  trailer = temp

print(f'The maximum day-on-day increase has been {max_day_on_day_change} degrees')
```

Run it on [Pythontutor](https://pythontutor.com/visualize.html#code='''%0AFind%20the%20maximum%20%28resp.%20minimum%29%20value%20change%20in%20a%20sequence%0A%0AAlgorithmic%20technique%3A%20the%20trailer%20variable%0A'''%0A%0Atemperatures_this_month%20%3D%20%5B27,%2021,%2016,%2021,%2019,%2018,%2019,%2012,%2015,%2012%5D%0A%0A'''%0AQuestion%3A%20%0Awhich%20day%20of%20the%20month%20has%20seen%20%0Athe%20steepest%20temperature%20change%20%28either%20increasing%20or%20decreasing%29%3F%0A'''%0A%0A%23%20start%20with%20the%20minimum%20possible%20value%0Amax_day_on_day_change%20%3D%200%0A%0A%23%20initialise%20the%20trailer%20variable%0Atrailer%20%3D%20temperatures_this_month%5B0%5D%0A%0Afor%20temp%20in%20temperatures_this_month%3A%0A%0A%20%20current_change%20%3D%20temp%20-%20trailer%0A%20%20%0A%20%20if%20abs%28current_change%29%20%3E%20max_day_on_day_change%3A%0A%20%20%0A%20%20%20%20max_day_on_day_change%20%3D%20abs%28current_change%29%20%23%20a%20new%20max%20is%20found%0A%0A%20%20%23%20we%20are%20finished%20with%20this%20value,%20assign%20it%20to%20the%20trailer%0A%20%20trailer%20%3D%20temp%0A%0Aprint%28f'The%20maximum%20day-on-day%20increase%20has%20been%20%7Bmax_day_on_day_change%7D%20degrees'%29%0A%0A%0A%0A&curInstr=49&matrixMode=true&mode=display&origin=opt-frontend.js&py=311)

---

## Quiz

Complete code for searching a given number in a sequence

```python
KEY = 22

mylist = [1, 6, 3, 9, 10]

___ item ___ mylist:
  if ___ == ___:
    found = True
  else:
    found = False
```
